# Generated by Django 2.0.6 on 2018-06-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_auto_20180630_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RenameField(
            model_name='drinktype',
            old_name='drink_type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='drinktype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeshop.Category'),
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeshop.DrinkType'),
        ),
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeshop.Size'),
        ),
    ]
