# Generated by Django 2.0.6 on 2018-06-30 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 14, 42, 54, 964370, tzinfo=utc), verbose_name='order_timestamp'),
            preserve_default=False,
        ),
    ]
